service: comunity-shelter

provider:
  name: aws
  runtime: nodejs18.x

functions:

    hello:
        handler: services/hello.hello
        events:
          - http:
              path: hello
              method: get

    createShelter:
        handler: services/createShelter.createShelter
        events:
          - http:
              path: createShelter
              method: post
        timeout: 30
    
    updateOcuppancy:
        handler: services/updateOcuppancy.updateOcuppancy
        events:
          - http:
              path: shelter/updateOcuppancy/{comunityShelterId}
              method: put
        timeout: 30

    getShelter:
        handler: services/getShelter.getShelter
        events:
          - http:
              path: shelter
              method: get
        timeout: 30

plugins:
  - serverless-offline

custom:
    serverless-offline:
        port: 3000
